---
title: ""
---

[Hier geht es zurück zur Übersicht der Projekte](projects.qmd)

## Entwicklung sozialer Beziehungen in Schulklasse und Sportunterricht

Herzlich Willkommen auf der Website zum Projekt \"Entwicklung sozialer Beziehungen in Schulklasse und Sportunterricht\" des Forschungsprogramms Soziale Netzwerke im Sportunterricht (SoNiS) des [Instituts für Sport und Sportwissenschaft der Universität Heidelberg](https://www.issw.uni-heidelberg.de/).

Auf diesen Seiten finden Sie alle Informationen über die Planung, Durchführung und Ziele des Projekts. Wenn Sie an der Studie teilnehmen wollen, bitte kontaktieren Sie den Studienleiter [Cornelius Holler](https://www.issw.uni-heidelberg.de/personal/homepage/holler_c.html) oder den Projektleiter [Prof. Dr. Rüdiger Heim](https://www.issw.uni-heidelberg.de/personal/homepage/heim_r.html) über die unten stehenden Kontaktmöglichkeiten.

## Informationen über die Studie

## Informationen zum Datenschutz und zur Erhebungsmethodik

## Dokumente zum Download

## Kontakt

## 
