---
title: "Publications"
---

## Articles in Peer-Reviewed Journals

Schüßler, A., **Holler, C.**, & Hill, Y. (2025). Do You Prefer to Collaborate with Students Pursuing the same Goals? A Network Analysis of Physical Education Classes, *British Journal of Educational Psychology*. [https://doi.org/10.1111/bjep.12757](https://doi.org/10.1111/bjep.12757){.uri target="_blank"}

**Holler, C.**, & Schüßler, A. (2024). Gauging Acceptance: A Multifaceted Examination of Physical Ability and Its Role for Peer Networks in Adolescent Physical Education. *Journal of Early Adolescence*. [https://doi.org/10.1177/02724316241265459](https://doi.org/10.1177/02724316241265459){.uri target="_blank"}

Heim, R., Schüßler, A., &, **Holler, C.** (2023). Peerbeziehungen in der Sporthalle -- Soziale Netzwerke im Sportunterricht \[Peer relations in the gym -- Social networks in Physical Education classes\]. *Zeitschrift für sportpädagogische Forschung*, *11*(1), 3--28. [https://doi.org/10.5771/2196-5218-2023-1-5](https://doi.org/10.5771/2196-5218-2023-1-5){.uri target="_blank"}

## Conference Contributions

### Presentations

**Holler, C.** & Veenstra, R. (2025). *The co-evolution of friendships, team partner ties and physical ability in grade 5 physical education*. Presentation at the SUNBELT Conference by the International Network for Social Network Analysis (INSNA) from June 23-29, 2025 in Paris, France.

**Holler, C.**, Schüßler, A., & Heim, R. (2025) *Leistungsperspektiven und ihre Rollen für Peernetzwerke im Sportunterricht* \[Perspectives on performance and their roles for peer networks in physical education\]. Presentation at the 12th conference of the Society for Empirical Educational Research (GEBF) from January 27-29, 2025 in Mannheim, Germany.

Schüßler, A., **Holler, C.**, & Hill, Y. (2024). *Exploring Goal Orientation in Peer Networks: The Role of Multidimensional Achievement Goals in Physical Education*. Presentation at the SUNBELT Conference by INSNA from June 24-30, 2024 in Edinburgh, Scotland.

**Holler, C.** (2024). *Veridikalität des sportunterrichtlichen Selbstkonzeptes und ihre Effekte auf die Anstrengungsbereitschaft und soziale Eingebundenheit im Sportunterricht* \[Veridicality of the physical education self-concept and it's effects on the engagement and social embeddedness in physical education\]. Presentation at the 37th yearly conference by the German Society of Sport Science (dvs) section sports pedagogy from May 30 - June 1, 2024 in Essen, Germany.

**Holler, C.** &, Schüßler, A. (2023). *Peerbeziehungen in der Schulklasse - Soziale Netzwerke im (Sport-)Unterricht* \[Peer relations in the gym - Social networks in physical education classes\]. Presentation at the autumn conference of the section "Sociological Network Science" of the German Sociological Association (GSA) on September 15-16, 2023 in Cologne, Germany.

**Holler, C.** (2023). *Social networks, external and self-assessments of performance in physical education*. Presentation at the 7th European Conference on Social Networks by INSNA from September 4-8, 2023 in Ljubljana, Slovenia.

**Holler, C.** (2023). *Soziale Netzwerke, Fremd- und Selbsteinschätzungen der sportunterrichtlichen Leistungsfähigkeit* \[Social networks, external and self-assessments of performance in physical education\]*.* Presentation at the 36th yearly conference by the German Society of Sport Science (dvs) section sports pedagogy from June 8-10, 2023 in Hamburg, Germany.

Heim, R., &, **Holler C.** (2022). *Peerbeziehungen in der Schulklasse. Soziale Netzwerke im (Sport-) Unterricht* \[Peer relations in the gym - Social networks in (physical) education classes\]*.* Presentation at the Subject Didactics Conference 2022 by the German and Austrian Societies of Subject Didactics (GFD and ÖGFD) from August 29-31, 2022 in Vienna, Austria.

Schüßler, A., &, **Holler, C.** (2021). *Soziale Netzwerke im Sportunterricht* \[Social networks in physical education\]. Presentation at the yearly conference of the German Society of Network Science (DGNet) from September 6-7, 2021 in Bayreuth, Germany.

### Poster

**Holler, C.** & Veenstra. R. (2025) *Die Entwicklung von Freundschaften und Teampartnerschaften in Abhängigkeit von der wahrgenommenen Leistung* \[The development of friendships and team partner ties in relation to perceived performance\]. Poster at the 38th yearly conference by the German Society of Sport Science (dvs) section sports pedagogy from May 1-3, 2025 in Leipzig, Germany. [Link (ger)](poster_dvs2025.qmd)

**Holler, C.**, Schüßler, A., &, Heim, R. (2022). *Analyse des Wahlverhaltens von Schüler:innen in typischen sportunterrichtlichen Kontexten* \[Analysis of the nominations of students in typical collaboration settings in physical education\]*.* Poster at the 35th yearly conference by the dvs section sports pedagogy from June 16-18, 2022 in Münster, Germany. [Link (ger)](poster_dvs2022.qmd)
