---
title: Heidees Open Streams
---

[Back to the overview](/private/ultimate_frisbee.qmd)

Here are some of the streamed games I found of the Heidees Open team. Please note that this is not meant as an exhaustive list. If you found a video that I should add, please write me a message!

# Outdoor

## 2024

### Heidees vs. Munic Masters Open Pool B at the German Championships 2024 in Nuremberg, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/VqGFhPKdvzA"></iframe>

</center>
```
### Heidees vs. 7 Schwaben Pool B at the German Championships 2024 in Nuremberg, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/hiDxg4TxGvU"></iframe>

</center>
```
### Heidees vs. FrankN Pool B at the German Championships 2024 in Nuremberg, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/NsuiPsTE1dw"></iframe>

</center>
```

### Heidees vs. Hardfish quarter final at the DFV Pokal 2024 in Gemmrigheim, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/8BmfVWOIkoQ"></iframe>

</center>
```
## 2023

### Heidees vs. Wall City semi-final at the German Championships 2023 in Marburg, Germany
```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/7VV1b98iS0A"></iframe>

</center>
```

### Heidees vs. BORA Pool B at the German Championships 2023 in Marburg, Germany
```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/iNYBJxuYUeE"></iframe>

</center>
```

### Heidees vs. Lahntalknaben Pool B at the German Championships 2023 in Marburg, Germany
```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/7MdbTcJl7ms"></iframe>

</center>
```

### Heidees vs. WaldStadt Pool B at the German Championships 2023 in Marburg, Germany
```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/shAdH0rBDnA"></iframe>

</center>
```

### Heidees vs. BFD La Fotta quarter final at the Elite Invite 2023 in Bern, Switzerland

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/CKYlhZfkpvQ"></iframe>

</center>
```
### Heidees vs. FrankN match for 5th place at the DFV Pokal 2023 in Massenbach, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/eMHHZFdhrUI"></iframe>

</center>
```
### Heidees vs. Ars Ludendi semi-final for 5th place at the DFV Pokal 2023 in Massenbach, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/gcb7RynmRRk"></iframe>

</center>
```
### Heidees vs. MUC cross-over game at the DFV Pokal 2023 in Massenbach, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/rs9q-NaTzrk"></iframe>

</center>
```
## 2022

### Heidees vs. Ranelagh semi final at the EUCF 2022 in Caorle, Italy

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/CceJ5t3VhjY"></iframe>

</center>
```
### Heidees vs. Bad Skid at the German Championships 2022 in Neuss, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/MWKhyFzVCMM"></iframe>

</center>
```
### Heidees vs. Wall City Final at the German Championships 2022 in Neuss, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/hm0FkXI1dMw"></iframe>

</center>
```
### Heidees vs. Bad Skid Game for 3rd Place at the DFV Pokal 2022 in Massenbach, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/BIY6qoyMALk"></iframe>

</center>
```
## 2021

### Heidees vs. Bad Skid Qualification Tournament for WUCC 2021 in Strausberg, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/MyJ-8IH5ISU"></iframe>

</center>
```
### Heidees vs. Bad Skid at the Restart DM 2021 in Massenbach, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/txnpnv67aTA"></iframe>

</center>
```
# Indoor

## 2024

### Heidees vs. Hässliche Erdferkel semi final at the German Indoor Championship 2024 in Gemmrigheim, Germany

```{=html}
<center>

    <iframe width="640" height="360" src="https://www.youtube.com/embed/TJZ9-5TU9GI"></iframe>

</center>
```
